### ISSUE TITLE
how we should link to some URL

### ISSUE THREAD

**Issue by soltanireza65** [pondersource/soukai-solid-utils#4]
tooked from @NoelDeMartin Feadback PR 

I changed the declaration for Bookmark.link to a FieldType.Key because that's what I think it should be looking at the vocab documentation. I looked [at your documentation](https://pdsinterop.org/conventions/bookmark/), and I'm not sure the example is right. I think the link to google should be <https://www.google.com>, rather than "https://www.google.com". But maybe I'm wrong, if that's the case then it's fine to declare it as a string.

[Link to PR](https://github.com/pondersource/soukai-solid-data-modules/pull/1)

**Comment by itsrezasoltani** [comment]
fixed with changes in:
[Link to implementation](https://pdsinterop.org/conventions/bookmark/)

**Comment by itsrezasoltani** [comment]
with the latest changes offered by Noel, it's still not fixed and links are inside double quotes and not <>
desired: <https://www.google.com>
what we have: "https://www.google.com"

**Comment by NoelDeMartin** [comment]
I see there is a `Bookmark.test.ts` file but I don't think it's executed, I'd recommend writing tests to make it easier for others to reproduce.

For example, if you had a test reproducing this situation (that the url is being serialized as a string rather than a url), I may be able to help without spending too much time trying to reproduce it.

**Comment by itsrezasoltani** [comment]
> I see there is a `Bookmark.test.ts` file but I don't think it's executed, I'd recommend writing tests to make it easier for others to reproduce.
> 
> For example, if you had a test reproducing this situation (that the url is being serialized as a string rather than a url), I may be able to help without spending too much time trying to reproduce it.

I have a plan to create the test cases, in [Link to issue](https://github.com/pondersource/soukai-solid-data-modules/issues/2)

but I just looked at your Movie model in media Kraken [Link to Movie Model](https://github.com/NoelDeMartin/media-kraken/blob/b9ac08c80acd8b9949e3f17df141fc805f98b15a/src/models/soukai/Movie.ts#L37C12-L37C12) you have implemented it in same way
and this is the document created by that model
```turtle
@prefix : <#>.
@prefix dct: <http://purl.org/dc/terms/>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix schem: <https://schema.org/>.

:it
    a schem:Movie;
    dct:created "2020-07-17T16:40:24Z"^^xsd:dateTime;
    dct:modified "2023-11-07T20:49:45Z"^^xsd:dateTime;
    schem:datePublished "1957-04-10T00:00:00Z"^^xsd:dateTime;
    schem:description
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.";
    schem:image
    "https://image.tmdb.org/t/p/w500/7sf9CgJz30aXDvrg7DYYUQ2U91T.jpg";
    schem:name "12 Angry Men";
    schem:sameAs
        "https://www.imdb.com/title/tt0050083",
        "https://www.themoviedb.org/movie/389".
```
as you see image URL (schem:image) is a string

**Comment by NoelDeMartin** [comment]
Yeah, that is some code I did a long time ago and it's not completely right. I have to fix it, but the problem with changing it in an existing application is that I have to make sure that it keeps working after the change.

If you look at the Movie model I have in the `soukai-solid` library you'll see that it's typed as a `FieldType.Key` and it works: [Movie.ts](https://github.com/NoelDeMartin/soukai-solid/blob/main/src/testing/lib/stubs/Movie.schema.ts#L22).

In your case, you should be able to fix it by declaring it as a `FieldType.Key` rather than `FieldType.Any`.

**Comment by itsrezasoltani** [comment]
I just wanted to be in the same line with your approach to developing apps
so I've fixed it to work as you expected it
